stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.quartz: 
  tags:
    - shell
    - quartz
  variables:
    CUSTOM_CI_BUILDS_DIR: "/usr/workspace/hiop/gitlab_ci/quartz/${CI_PIPELINE_ID}"
    MY_CLUSTER: quartz

.lassen: 
  tags:
    - shell
    - lassen
  variables:
    CUSTOM_CI_BUILDS_DIR: "/usr/workspace/hiop/gitlab_ci/lassen/${CI_PIPELINE_ID}"
    MY_CLUSTER: lassen

.llnl_script_template: 
  stage: build
  script:
    - |
      # Don't clean up this working directory - we need some of these files for
      # testing
      echo "CI_PIPELINE_ID = ${CI_PIPELINE_ID}"
      echo "CI_JOB_ID = ${CI_JOB_ID}"
      echo "CUSTOM_CI_BUILDS_DIR = ${CUSTOM_CI_BUILDS_DIR}"
      set -xv
      mkdir -p "$CUSTOM_CI_BUILDS_DIR"
      cp -R ./* "$CUSTOM_CI_BUILDS_DIR"
      cd "$CUSTOM_CI_BUILDS_DIR"
      ./BUILD.sh --build-only || exit 1

.llnl_test_script_template: 
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - |
      echo "CI_PIPELINE_ID = ${CI_PIPELINE_ID}"
      echo "CI_JOB_ID = ${CI_JOB_ID}"
      echo "CUSTOM_CI_BUILDS_DIR = ${CUSTOM_CI_BUILDS_DIR}"
      set -xv
      cd "$CUSTOM_CI_BUILDS_DIR"
      ./BUILD.sh --test-only
      res=$?
      exit $res
  after_script:
    - |
      cd "$CUSTOM_CI_BUILDS_DIR/.."
      rm -rf "$CUSTOM_CI_BUILDS_DIR"
      rm -rf "/usr/workspace/hiop/gitlab_ci/scripts/$CI_RUNNER_SHORT_TOKEN"

.llnl_test_jsrun_script: 
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - |
      echo "CI_PIPELINE_ID = ${CI_PIPELINE_ID}"
      echo "CI_JOB_ID = ${CI_JOB_ID}"
      echo "CUSTOM_CI_BUILDS_DIR = ${CUSTOM_CI_BUILDS_DIR}"
      set -xv
      cd "$CUSTOM_CI_BUILDS_DIR"
      lalloc 1 -G hiop -W 35 -q pbatch ./BUILD.sh --test-only
      res=$?
      exit $res
  after_script:
    - |
      cd "$CUSTOM_CI_BUILDS_DIR/.."
      rm -rf "$CUSTOM_CI_BUILDS_DIR"
      rm -rf "scripts/$CI_RUNNER_SHORT_TOKEN"
      
# For LLNL/quartz CI
build_on_quartz:
  extends:
    - .quartz
    - .llnl_script_template

# For LLNL/quartz CI
test_on_quartz:
  extends:
    - .quartz
    - .llnl_test_script_template
  needs: ['build_on_quartz']

# For LLNL/lassen CI
build_on_lassen:
  extends:
    - .lassen
    - .llnl_script_template

# For LLNL/lassen CI
test_on_lassen:
  extends:
    - .lassen
    - .llnl_test_jsrun_script
  needs: ['build_on_lassen']
